name: Build
on: push

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - shell: bash
              run: .github/workflows/build.sh

